import os
from datetime import datetime, date
import numpy as np


DF_COLORS = {
    "first": "limegreen",
    "second": "forestgreen",
    "third": "gold",
    "fourth": "orange",
    "fifth": "orangered",
    "inf_color": "pink",
}

PLOTTING = {
    "colors_fase1": {
        "precio_spot": "olivedrab",
        "price_pred": "firebrick",
        "demanda": "peru",
        "prod_solar": "gold",
        "prod_eolica": "steelblue",
        "demanda_prevision": "#8C564B",
        "eolica_prevision": "#990099",
        "demanda_residual": "sandybrown",
        "rampa": "darkred",
        "solar_prevision": "#FF7F0E",
        "EUA": "deeppink",
        "precio_gas": "mediumorchid",
        "col_nuclear": "#1CBE4F",
        "col_combined_cycle": "#7049E1",
        "col_cogeneration": "#E19949",
        "col_hydraulic": "#49E1E1",
        "col_interconexion_francia": "#4982E1",
        "col_interconexion_global": "#C049E1",
        "col_interconexion_marruecos": "#F1A831",
        "ARIMA": "#B82E2E",
        "RIDGE": "#316395",
        "XGBoost": "royalblue",
        "LGBM": "#FF9900",
        "CatBoost": "royalblue",
    },
    "linestyle": {
        "price_real": "solid",
        "price_pred": "solid",
        "demand": "solid",
        "solar": "solid",
        "wind": "solid",
        "co2": "solid",
        "gas": "solid",
        "Ridge": "solid",
        "XGBoost": "dashed",
        "LGBM": "dotted",
        "CatBoost": "dashdot",
    },
    "colors_fase2": {
        "precio": "olivedrab",
        "energia": "darkorange",
        "Solar": "gold",
        "Eólica": "steelblue",
        "Nuclear": "#1CBE4F",
        "Ciclo Combinado": "#7049E1",
        "Hidráulica": "#49E1E1",
        "RE Hidráulica": "#FE00FA",
        "Carbón de Importación": "#85660D",
        "Hidráulica Bombeo": "#3283FE",
        "Carbón": "#F7E1A0 ",
        "Térmica Renovable": "#FBE426",
        "Térmica no Renovable": "#E2E2E2",
        "RE CUR": "#2C2F37",
        "Unidad Genérica": "#C4451C",
        "Almacenamiento Venta": "#DEA0FD",
        "Geotérmica": "#FE00FA",
        "Importaciones": "#325A9B",
        "CUR Hidráulica": "#49E1E9",
        "CUR Eólica": "darkblue",
        "CUR Solar": "orange",
        "CUR Térmica Renovable": "brown",
        "CUR Térmica no Renovable": "olive",
    },
}
